/*
 * NIS2 API Endpoints
 * This document defines all the nis2 api endpoints
 *
 * OpenAPI spec version: 0.9.1
 * Contact: guillem@nemeurope.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.LockFundsInfo;
import java.io.IOException;

/**
 * LockFundsInfoDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-30T14:24:32.577Z")
public class LockFundsInfoDTO {
  @SerializedName("lock")
  private LockFundsInfo lock = null;

  public LockFundsInfoDTO lock(LockFundsInfo lock) {
    this.lock = lock;
    return this;
  }

   /**
   * Get lock
   * @return lock
  **/
  @ApiModelProperty(required = true, value = "")
  public LockFundsInfo getLock() {
    return lock;
  }

  public void setLock(LockFundsInfo lock) {
    this.lock = lock;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LockFundsInfoDTO lockFundsInfoDTO = (LockFundsInfoDTO) o;
    return Objects.equals(this.lock, lockFundsInfoDTO.lock);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lock);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LockFundsInfoDTO {\n");
    
    sb.append("    lock: ").append(toIndentedString(lock)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

