/*
 * NIS2 API Endpoints
 * This document defines all the nis2 api endpoints
 *
 * OpenAPI spec version: 0.9.1
 * Contact: guillem@nemeurope.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.SecretLockInfo;
import java.io.IOException;

/**
 * SecretLockInfoDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-30T14:24:32.577Z")
public class SecretLockInfoDTO {
  @SerializedName("mosaicId")
  private SecretLockInfo mosaicId = null;

  public SecretLockInfoDTO mosaicId(SecretLockInfo mosaicId) {
    this.mosaicId = mosaicId;
    return this;
  }

   /**
   * Get mosaicId
   * @return mosaicId
  **/
  @ApiModelProperty(value = "")
  public SecretLockInfo getMosaicId() {
    return mosaicId;
  }

  public void setMosaicId(SecretLockInfo mosaicId) {
    this.mosaicId = mosaicId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecretLockInfoDTO secretLockInfoDTO = (SecretLockInfoDTO) o;
    return Objects.equals(this.mosaicId, secretLockInfoDTO.mosaicId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mosaicId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecretLockInfoDTO {\n");
    
    sb.append("    mosaicId: ").append(toIndentedString(mosaicId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

